// ENTER IN THE FORM
// "key"=>"translation"
// ALWAYS ALIGN THE 'KEYS' WITH THE ENGLISH KEYS

"username"=>"nombre de usuario",
"password"=>"contraseña",
"login"=>"entrar",
"loginFailed"=>"<span class=\"error\">error al autentificarse</span>",
"openSource"=>"Un sistema de<br>gestión de proyectos OpenSource<br>",
"forgotPassword"=>"Ayuda.  No recuerdo mi nombre o contraseña.",
"Help"=>"Ayuda",

// ALWAYS PUT A COMMA (,) AFTER THE LAST ENTRY