// ENTER IN THE FORM
// "key"=>"translation"
// ALWAYS ALIGN THE 'KEYS' WITH THE ENGLISH KEYS

"username"=>"nombre del usuario",
"password"=>"contraseña",
"login"=>"conexión",
"loginFailed"=>"<span class=\"error\">la conexión falló</span>",
"openSource"=>"una fuente abierta<br>gerencia de proyecto<br>uso",
"forgotPassword"=>"Ayuda.  Me he olvidado de mi nombre y contraseña del usuario.",
"Help"=>"Ayuda",

// ALWAYS PUT A COMMA (,) AFTER THE LAST ENTRY