<?= $this->doctype('XHTML1_TRANSITIONAL') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php
	// Trigger default controller to prepare layout variables
	// Theres probably a better way to do this. Extend Zend_View ?
	$this->action('preparelayout','index');
	$layout = $this->layout();
	
	$this->headMeta()->appendName('Description', 'dotProject Default Style');
	$this->headMeta()->appendName('Version', $layout->version);
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html');
	
	$this->headTitle($layout->page_title);
	
	$this->headLink()->appendStylesheet($layout->baseUrl.'/css/print.css', 'print');
	$this->headLink()->appendStylesheet($layout->baseUrl.'/calendar.css');
	$this->headLink()->appendStylesheet($layout->baseUrl.'/css/'.$layout->uistyle.'/main.css');
	$this->headLink()->appendStylesheet($layout->baseUrl.'/css/calendar/calendar-dp.css');
	$this->headLink()->appendStylesheet('./style/'.$layout->uistyle.'/main.css');	

	$this->headLink()->appendAlternate($layout->baseUrl.'/img/'.$layout->uistyle.'/favicon.ico', 'image/ico', 'shortcut icon');
	
	$this->headStyle()->appendStyle('./style/'.$layout->uistyle.'/main.css');
	
	$this->headScript()->appendScript($layout->baseUrl.'/lib/overlib/overlib.js');
	$this->headScript()->appendScript($layout->baseUrl.'/js/dPcommon.js');
	
	// Print out HEAD sections
	?>
	<?=$this->headMeta(); ?>
	<?=$this->headTitle(); ?>
	<?=$this->headLink(); ?>
	<?=$this->headStyle(); ?>
	<?=$this->headScript(); ?>
</head>
<body onload="this.focus();">
<!--  	{popup_init src="`$baseUrl`/lib/overlib/overlib.js"} -->
<!-- 
<table width="100%" cellspacing="0" cellpadding="0">
<tr>
	<td> -->
	
	<div style="position: relative; height: 26px;">
		<div style="position: absolute; top: 0; left: 0; height: 26px; width: 100%; background:url('<?=$layout->baseUrl ?>/img/<?=$layout->uistyle ?>/titlegrad.jpg');">
		<!-- style=" -->
			<strong>
				<a style="color: white" href="<?=$layout->baseUrl ?>"><?=$layout->page_title ?></a>
			</strong>
		</div>
		<div class="nav" style="position: absolute; top: 0; right: 0; height: 20px; padding: 3px; width: 120px; background-color: #f0f0f0;">
			<a href="http://www.dotproject.net/"<?php if ($layout->dialog) {?>} target="_blank"<?} ?>>
				<img src="<?=$layout->baseUrl ?>/img/<?=$layout->uistyle ?>/dp_icon.gif" alt="dotProject icon" border="0" />
			</a>
		</div>
	</div>
<!--  
	</td>
</tr> -->
<?php if (!$layout->dialog) { ?>
<!-- 
<tr>
	<td class="nav" align="left">
	<table cellpadding="3" cellspacing="0" width="100%">
	<tr>
		<td> -->
<div class="nav" style="width: 100%; border: 1px solid #848284; background-color: #d5d3ce; color: #FFFFFF; padding: 5px; font-family: Osaka, verdana,Sans-Serif;
	font-size: 8pt;">
	<?php foreach ($layout->modules as $mod) { ?>
		<a href="<?=$layout->baseUrl ?>/<?=$mod['mod_directory'] ?>/"><?=$mod['mod_ui_name']?></a>
		<?php if ($mod != $layout->modules[count($layout->modules)-1]) { ?> | <?} ?>
	<?php } ?>

		<form name="frm_new" method="get" action="./index.php" style="float: right">
		<?=$layout->new_item ?>
		<!-- {dParraySelect array=$new_item name='m' extras='style="font-size:10px" onchange="f=document.frm_new;mod=f.m.options[f.m.selectedIndex].value;if(mod) f.submit();"' value='' translation=true}
		-->
	<?php if ($layout->company_id) { ?>
		<input type="hidden" name="company_id" value="<?=$layout->company_id ?>" />
	<?php } ?>
	<?php if ($layout->task_id) { ?>	
		<input type="hidden" name="task_parent" value="<?=$layout->task_id ?>" />
	<?php } ?>
	<?php if ($layout->file_id) { ?>
		<input type="hidden" name="file_id" value="<?=$layout->file_id ?>" />
	<?php } ?>
		<input type="hidden" name="a" value="addedit" />
		</form>
</div>
		</td>
	</tr>
	</table>
	</td>
</tr>
<tr>
	<td>
		<table cellspacing="0" cellpadding="3" border="0" width="100%">
		<tr>
			<td width="100%"><?=$this->translate('Welcome')?> <?=$layout->user_name ?></td>
			<td nowrap="nowrap">
				<a href="#" onclick="javascript:window.open('<?=$layout->baseUrl ?>/help/', 'contexthelp', 'width=400, height=400, left=50, top=50, scrollbars=yes, resizable=yes')"><?=$this->translate('Help')?></a> |
				<a href="<?=$layout->baseUrl ?>/admin/viewuser/?user_id=<?=$layout->user_id ?>"><?=$this->translate('My').' '.$this->translate('Info'); ?></a> |
	<?php if ($layout->access_calendar) { ?>
	         <b><a href="<?=$layout->baseUrl ?>/tasks/todo/"><?=$this->translate('Todo')?></a></b> |
				<a href="<?=$layout->baseUrl ?>/calendar/day_view/?date={dPdateFormat date='now' format='db'}"><?=$this->translate('Today')?></a> |
	<?php } ?>
	<?php if ($layout->access_links) {?>
				<a href="<?=$layout->baseUrl ?>/links/"><?=$this->translate('Links')?></a> |
	<?php } ?>
				<a href="javascript:void(0);" onclick="window.print();return false;"><?=$this->translate('Print')?></a> |
				<a href="<?=$layout->baseUrl ?>/logout/"><?=$this->translate('Logout')?></a>
			</td>
		</tr>
		</table>
	</td>
</tr>
<?php } // dialog ?>
</table>
<table width="100%" cellspacing="0" cellpadding="4" border="0">
<tr class="print">
	<td valign="top" align="left" width="98%">
	<?=$layout->msg ?>
	<?php if ($layout->titleBlock) { 
			require_once($layout->baseDir.'/code/style/_smarty/titleBlock.html'); 
		} // include titleblock.html 
		?>
	<!--  render titleblock here -->
	<!--  render main content -->
	<?php echo $layout->content; ?>
	<?php if ($tabBox) { 
		require_once($layout->baseDir.'/code/style/_smarty/tabBox.html');
	} ?>
	<?php echo $layout->$msg; ?>
	</td>
</tr>
</table>
</body>
</html>