<?php
$this->HeadLink()->appendStylesheet($this->baseUrl.'/css/dp-view.css');

$this->HeadScript()->appendFile('/js/yui/build/yahoo-dom-event/yahoo-dom-event.js');
$this->HeadScript()->appendFile('/js/yui/build/connection/connection.js');
$this->HeadScript()->appendFile('/js/yui/build/element/element-beta-min.js');

//$this->HeadScript()->appendFile('/js/yui/build/treeview/treeview.js');
$this->HeadScript()->appendFile('/js/yui/build/datatable/datatable-min.js');

//$this->main->viewWillRender($this);
?>

<?=$this->DataTable();?>

<?

//=$this->main;
?>