<?php 
	// IE injects whitespace in form tag
	//$this->headStyle()->appendStyle('form {					margin: 0;');

	$this->headLink()->appendStylesheet($this->baseUrl.'/css/zendform.css');
	
	$this->headStyle()->appendStyle('div#logincontainer {	margin-top: 50px;
															margin-left: auto; 
															margin-right: auto; 
															width: 305px; 
															border: solid #08245b 2px; 
															background: #d6ebff; 
															padding: 0px }');
		$this->headStyle()->appendStyle('input#login { 		float: right; }');
		$this->headStyle()->appendStyle('div#loginheader { 	background-color: #08245b;
															color: white;
															border: outset #D1D1CD 1px; 
															padding: 5px;
															text-align: center;
																	}');
		$this->headStyle()->appendStyle('fieldset#submitgrp dt { display: none; }');
		$this->headStyle()->appendStyle('input#dotproject { border-style: none; }');
?>
<div id="logincontainer">
	<div id="loginheader"><em><?=$this->config['company_name']?></em></div>
	<?=$this->form?>
	<?=$this->form->getDisplayGroup('login')?>
	<?=$this->form->getDisplayGroup('submission')?>
	<div id="info">
		<p>
		<a href="#" onclick="f=document.loginform;f.lostpass.value=1;f.submit();">
		<?=$this->translate('Help! I\'ve forgotten my password!'); ?></a>
		</p>
		<p>
		<a href="<?=$config['site_terms']?>" target="_new">
		<?=$this->translate('TERMS AND CONDITIONS OF ACCESSING THIS SITE');?></a>
		</p>
	</div>
</div>

<?php if ($this->version) { ?>
<div align="center">
	<span style="font-size:7pt">Version <?=$this->version?></span>
</div>
<?php } ?>

<div align="center">
	<span class="error">&nbsp;<?=$this->message ?></span>
<?php if ($this->phpversion < '4.1') { ?>
	<br /><span class="warning">WARNING: dotproject is NOT SUPPORTED for this PHP Version (<?=$this->phpversion?>)</span>
<?php } ?>
<?php if (!$this->mysql) { ?>
	<br /><span class="warning">WARNING: PHP may not be compiled with MySQL support.  This will prevent proper operation of dotProject.  Please check you system setup.</span>
<?php } ?>
</div>
<center>
	* <?=$this->translate('You must have cookies enabled in your browser'); ?><br />
</center>
<div style="text-align: center; display: none;" id="terms">
	<?=$config['site_terms']?>
</div>

<script type="text/javascript">
<!-- // Select all text in the user box (if any) for easier login. If password is saved, hitting enter will login user.
setTimeout("document.loginform.username.select()", 500);
-->
</script>