<table width="50%" border="0" cellpadding="0" cellspacing="5" align="left">
<tr>
	<td width="42">
		<img src="<?php echo $this->makeUrl('img', 'rdf2.png');?>" width="42" height="42"/>
	</td>
	<td align="left" class="subtitle">
		<?php echo $this->translate('Language Support'); ?>
	</td>
</tr>

<tr>
	<td>&nbsp;</td>
	<td align="left">
		<a href="<?=$this->Url(Array('action'=>'index', 'controller'=>'translation', 'module'=>'system')); ?>"><?=$this->translate('Translation Management'); ?></a>
	</td>
</tr>

<tr>
	<td>
		{dPshowImage src='./modules/system/images/myevo-weather.png' wsize=42 hsize=42}
	</td>
	<td align="left" class="subtitle">
		<?=$this->translate('Preferences'); ?>
	</td>
</tr>

<tr>
	<td>&nbsp;</td>
	<td align="left">
		<a href="<?=$this->Url(Array('module'=>'system', 'controller'=>'config', 'action'=>'index')); ?>"><?=$this->translate('System Configuration'); ?></a><br />
		<a href="<?=$this->Url(Array('action'=>'index', 'controller'=>'user', 'module'=>'system')); ?>"><?=$this->translate('Default User Preferences'); ?></a><br />
		<a href="<?=$this->Url(Array('action'=>'index', 'controller'=>'keys', 'module'=>'system')); ?>"><?=$this->translate('System Lookup Keys'); ?></a><br />
		<a href="<?=$this->Url(Array('action'=>'index', 'controller'=>'values', 'module'=>'system')); ?>"><?=$this->translate('System Lookup Values'); ?></a><br />
		<a href="<?=$this->Url(Array('action'=>'customfields', 'controller'=>'index', 'module'=>'system')); ?>"><?=$this->translate('Custom Field Editor'); ?></a><br />
		<a href="<?=$this->Url(Array('action'=>'index', 'controller'=>'billing', 'module'=>'system')); ?>"><?=$this->translate('Billing Code Table'); ?></a>
	</td>
</tr>

<tr>
	<td>
		{dPshowImage src='./modules/system/images/power-management.png' wsize=42 hsize=42}
	</td>
	<td align="left" class="subtitle">
		<?=$this->translate('Modules'); ?>
	</td>
</tr>

<tr>
	<td>&nbsp;</td>
	<td align="left">
		<a href="<?=$this->Url(Array('action'=>'index', 'controller'=>'modules', 'module'=>'system')); ?>"><?=$this->translate('View Modules'); ?></a>
	</td>
</tr>

<tr>
	<td>
		{dPshowImage src='./modules/system/images/main-settings.png' wsize=42 hsize=42}
	</td>
	<td align="left" class="subtitle">
		<?=$this->translate('Administration'); ?>
	</td>
</tr>

<tr>
	<td>&nbsp;</td>
	<td align="left">
		<a href="<?=$this->Url(Array('action'=>'index', 'controller'=>'roles', 'module'=>'system')); ?>"><?=$this->translate('User Roles'); ?></a>
	</td>
</tr>

<tr>
	<td>&nbsp;</td>
	<td align="left">
		<a href="<?=$this->Url(Array('action'=>'ldapcontacts', 'controller'=>'import', 'module'=>'system')); ?>"><?=$this->translate('Import Contacts'); ?></a>
	</td>
</tr>

</table>
